const mongoose = require('mongoose');
const Product = require('../models/Product');
require('dotenv').config();

const DEFAULT_SELLER_ID = new mongoose.Types.ObjectId('000000000000000000000000');

const products = [
  // Best Sellers Category
  {
    name: 'Daily Duo Bundle',
    price: 973,
    description: 'Essential daily skincare duo for your routine',
    images: ['https://img.freepik.com/premium-psd/skin-care-moisturizing-cosmetic-premium-products_99236-254.jpg'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 651,
    skinType: { normal: true, dry: true, oily: true, combination: true, sensitive: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1498,
    discount: 35
  },
  {
    name: 'Vitamin C Serum',
    price: 599,
    description: 'Brightening and antioxidant-rich serum',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'],
    category: 'best-sellers',
    rating: 4.7,
    numReviews: 428,
    skinType: { normal: true, dry: true, oily: true, combination: true },
    stock: 150,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 799,
    discount: 25
  },
  {
    name: 'Hydrating Face Cream',
    price: 449,
    description: 'Deep hydration for all skin types',
    images: ['https://plus.unsplash.com/premium_photo-1661630984481-e29093921ff7'],
    category: 'best-sellers',
    rating: 4.9,
    numReviews: 312,
    skinType: { normal: true, dry: true, combination: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 599,
    discount: 25
  },
  {
    name: 'Anti-Aging Night Cream',
    price: 799,
    description: 'Advanced anti-aging formula for overnight repair',
    images: ['https://images.pexels.com/photos/6621329/pexels-photo-6621329.jpeg'],
    category: 'best-sellers',
    rating: 4.6,
    numReviews: 245,
    skinType: { normal: true, dry: true, mature: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 20
  },
  {
    name: 'Gentle Cleansing Foam',
    price: 349,
    description: 'Soft and gentle cleansing foam for daily use',
    images: ['https://images.pexels.com/photos/6621334/pexels-photo-6621334.jpeg'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 189,
    skinType: { normal: true, sensitive: true },
    stock: 200,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 449,
    discount: 22
  },
  {
    name: 'Ultimate Skincare Bundle',
    price: 1499,
    description: 'Complete skincare routine in one package',
    images: ['https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg'],
    category: 'best-sellers',
    rating: 4.9,
    numReviews: 523,
    skinType: { normal: true, dry: true, oily: true, combination: true },
    stock: 50,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2499,
    discount: 40
  },
  {
    name: 'Brightening Eye Cream',
    price: 599,
    description: 'Targeted treatment for the delicate eye area',
    images: ['https://images.pexels.com/photos/6724350/pexels-photo-6724350.jpeg'],
    category: 'best-sellers',
    rating: 4.7,
    numReviews: 167,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 749,
    discount: 20
  },
  {
    name: 'Lip Care Set',
    price: 299,
    description: 'Complete lip care routine for soft, smooth lips',
    images: ['https://images.unsplash.com/photo-1564594326930-17381130fd2e'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 234,
    skinType: { all: true },
    stock: 150,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 399,
    discount: 25
  },
  {
    name: 'Acne Treatment Gel',
    price: 449,
    description: 'Targeted treatment for acne-prone skin',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be'],
    category: 'best-sellers',
    rating: 4.6,
    numReviews: 378,
    skinType: { oily: true, combination: true, acne_prone: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 549,
    discount: 18
  },
  {
    name: 'Sunscreen SPF 50',
    price: 499,
    description: 'High protection sunscreen for daily use',
    images: ['https://images.unsplash.com/photo-1576426863848-c21f53c60b19'],
    category: 'best-sellers',
    rating: 4.9,
    numReviews: 456,
    skinType: { all: true },
    stock: 200,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 649,
    discount: 23
  },
  {
    name: 'Collagen Boost Serum',
    price: 899,
    description: 'Advanced collagen-boosting formula',
    images: ['https://images.unsplash.com/photo-1573461160327-b450ce3d8e7f'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 289,
    skinType: { normal: true, dry: true, mature: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'Hydrating Toner',
    price: 399,
    description: 'Alcohol-free hydrating toner',
    images: ['https://images.unsplash.com/photo-1612817288484-6f916006741a'],
    category: 'best-sellers',
    rating: 4.7,
    numReviews: 178,
    skinType: { all: true },
    stock: 150,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 499,
    discount: 20
  },
  {
    name: 'Beauty Sleep Bundle',
    price: 1299,
    description: 'Complete nighttime skincare routine',
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b'],
    category: 'best-sellers',
    rating: 4.9,
    numReviews: 423,
    skinType: { all: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1999,
    discount: 35
  },
  {
    name: 'Pore Minimizing Mask',
    price: 549,
    description: 'Deep cleansing pore treatment mask',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 156,
    skinType: { oily: true, combination: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 699,
    discount: 21
  },
  {
    name: 'Lip Plumping Gloss',
    price: 299,
    description: 'Volumizing and hydrating lip treatment',
    images: ['https://images.unsplash.com/photo-1599305090598-fe179d501227'],
    category: 'best-sellers',
    rating: 4.7,
    numReviews: 267,
    skinType: { all: true },
    stock: 200,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 399,
    discount: 25
  },
  {
    name: 'Retinol Night Serum',
    price: 799,
    description: 'Advanced retinol treatment for overnight renewal',
    images: ['https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19'],
    category: 'best-sellers',
    rating: 4.9,
    numReviews: 345,
    skinType: { normal: true, dry: true, mature: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 20
  },
  {
    name: 'Glow Boost Kit',
    price: 1099,
    description: 'Complete skincare routine for radiant skin',
    images: ['https://images.unsplash.com/photo-1615397349754-cfa2066a298e'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 412,
    skinType: { all: true },
    stock: 70,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1599,
    discount: 31
  },
  {
    name: 'Exfoliating Scrub',
    price: 449,
    description: 'Gentle exfoliating treatment for smooth skin',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b'],
    category: 'best-sellers',
    rating: 4.7,
    numReviews: 198,
    skinType: { normal: true, combination: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 549,
    discount: 18
  },
  {
    name: 'Moisturizing Hand Cream',
    price: 249,
    description: 'Rich hand cream for soft, smooth hands',
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd'],
    category: 'best-sellers',
    rating: 4.6,
    numReviews: 145,
    skinType: { all: true },
    stock: 250,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 299,
    discount: 17
  },
  {
    name: 'Anti-Dark Spot Serum',
    price: 699,
    description: 'Targeted treatment for hyperpigmentation',
    images: ['https://images.unsplash.com/photo-1617897903246-719242758050'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 278,
    skinType: { all: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 899,
    discount: 22
  },
  {
    name: 'Hydrating Sheet Masks Set',
    price: 399,
    description: 'Set of hydrating sheet masks for instant glow',
    images: ['https://images.unsplash.com/photo-1567721913486-6585f069b332'],
    category: 'best-sellers',
    rating: 4.7,
    numReviews: 167,
    skinType: { all: true },
    stock: 150,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 499,
    discount: 20
  },
  {
    name: 'Neck Firming Cream',
    price: 599,
    description: 'Specialized treatment for neck and décolletage',
    images: ['https://images.unsplash.com/photo-1556227834-09f1de7a7d14'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 189,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 799,
    discount: 25
  },
  {
    name: 'Complete Beauty Box',
    price: 1999,
    description: 'Ultimate skincare collection for all needs',
    images: ['https://images.unsplash.com/photo-1631729371254-42c2892f0e6e'],
    category: 'best-sellers',
    rating: 4.9,
    numReviews: 534,
    skinType: { all: true },
    stock: 40,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2999,
    discount: 33
  },
  {
    name: 'Hyaluronic Acid Serum',
    price: 649,
    description: 'Deep hydrating hyaluronic acid serum',
    images: ['https://images.unsplash.com/photo-1592136957897-b2b6ca21e10d'],
    category: 'best-sellers',
    rating: 4.8,
    numReviews: 367,
    skinType: { all: true },
    stock: 110,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 849,
    discount: 24
  },
  {
    name: 'Glow Essentials Duo Kit',
    price: 1899,
    description: 'Essential duo for achieving a natural glow',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Web_pic001_400x.png?v=1671778694'],
    category: 'bundles',
    rating: 4.8,
    numReviews: 128,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2499,
    discount: 25
  },
  {
    name: 'Hydration Trio Set',
    price: 2499,
    description: 'Complete hydration routine with three essential products',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/rosaline---product-image2_1_400x.png?v=1676986731'],
    category: 'bundles',
    rating: 4.9,
    numReviews: 95,
    skinType: { all: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3299,
    discount: 30
  },
  {
    name: 'Anti-Aging Power Pack',
    price: 3299,
    description: 'Complete anti-aging skincare solution',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/SkinRescueBundle-web_400x.png?v=1675267403'],
    category: 'bundles',
    rating: 4.7,
    numReviews: 76,
    skinType: { mature: true, dry: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 4499,
    discount: 35
  },
  {
    name: 'Brightening Duo Kit',
    price: 1699,
    description: 'Powerful brightening treatment duo',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/Group1_400x.jpg?v=1690554340'],
    category: 'bundles',
    rating: 4.8,
    numReviews: 112,
    skinType: { all: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2299,
    discount: 30
  },
  {
    name: 'Acne Control Value Set',
    price: 2199,
    description: 'Complete acne treatment system',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Tinted-Lip-Treat-Bundle--product-image_400x.jpg?v=1681979111'],
    category: 'bundles',
    rating: 4.6,
    numReviews: 89,
    skinType: { oily: true, combination: true, acne_prone: true },
    stock: 75,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2999,
    discount: 40
  },
  {
    name: 'Complete Skincare Bundle',
    price: 4499,
    description: 'Full skincare routine in one package',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/hair-essential-duo---product-image-01_400x.jpg?v=1687524443'],
    category: 'bundles',
    rating: 4.9,
    numReviews: 154,
    skinType: { all: true },
    stock: 50,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 5999,
    discount: 45
  },
  {
    name: 'Morning Routine Trio',
    price: 2799,
    description: 'Essential morning skincare collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/finalmas_400x.jpg?v=1667896859'],
    category: 'bundles',
    rating: 4.7,
    numReviews: 67,
    skinType: { all: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3599,
    discount: 35
  },
  {
    name: 'Night Care Duo Kit',
    price: 1999,
    description: 'Overnight repair and renewal duo',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6372_400x.png?v=1716401109'],
    category: 'bundles',
    rating: 4.8,
    numReviews: 93,
    skinType: { all: true },
    stock: 70,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2599,
    discount: 30
  },
  {
    name: 'Luxury Skincare Collection',
    price: 5999,
    description: 'Premium skincare bundle for ultimate results',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/PicturePerfect_400x.png?v=1643889395'],
    category: 'bundles',
    rating: 4.9,
    numReviews: 45,
    skinType: { all: true },
    stock: 40,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 7999,
    discount: 40
  },
  {
    name: 'Sensitive Skin Duo',
    price: 1799,
    description: 'Gentle care for sensitive skin',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/serum-duo---product-image2_400x.png?v=1678266108'],
    category: 'bundles',
    rating: 4.7,
    numReviews: 78,
    skinType: { sensitive: true },
    stock: 95,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2399,
    discount: 25
  },
  {
    name: 'Pore Care Bundle',
    price: 2299,
    description: 'Complete pore care and cleansing system',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Ad-6webcopy_400x.jpg?v=1666955126'],
    category: 'bundles',
    rating: 4.6,
    numReviews: 112,
    skinType: { oily: true, combination: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2999,
    discount: 30
  },
  {
    name: 'Vitamin C Power Set',
    price: 2699,
    description: 'Brightening and antioxidant skincare set',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/intense-hydration-bundle-2_1_400x.png?v=1699996289'],
    category: 'bundles',
    rating: 4.8,
    numReviews: 89,
    skinType: { all: true },
    stock: 70,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3499,
    discount: 35
  },
  {
    name: 'Ultimate Glow Kit',
    price: 3999,
    description: 'Premium collection for radiant skin',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/ultimate-skin-corrector-bundle---product-image_400x.png?v=1677241431'],
    category: 'bundles',
    rating: 4.9,
    numReviews: 156,
    skinType: { all: true },
    stock: 55,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 5299,
    discount: 40
  },
  {
    name: 'Hydration Heroes Set',
    price: 2899,
    description: 'Ultimate hydration collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Saga_Rapid_Essential_400x.png?v=1675278467'],
    category: 'bundles',
    rating: 4.7,
    numReviews: 92,
    skinType: { dry: true, normal: true },
    stock: 75,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3799,
    discount: 30
  },
  {
    name: 'Radiance Boost Duo',
    price: 1999,
    description: 'Dual-action brightening system',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/rn-image_picker_lib_temp_b70d48be-e9f7-4dff-9083-9759bb65205f_400x.png?v=1714890118'],
    category: 'bundles',
    rating: 4.6,
    numReviews: 78,
    skinType: { all: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2599,
    discount: 25
  },
  {
    name: 'Anti-Aging Essentials',
    price: 4299,
    description: 'Complete anti-aging skincare system',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6372_400x.png?v=1716401109'],
    category: 'bundles',
    rating: 4.8,
    numReviews: 134,
    skinType: { mature: true, dry: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 5699,
    discount: 35
  },
  {
    name: 'Clear Skin Bundle',
    price: 2499,
    description: 'Complete acne and blemish control system',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Web_pic002_400x.png?v=1671778864'],
    category: 'bundles',
    rating: 4.7,
    numReviews: 167,
    skinType: { oily: true, acne_prone: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3299,
    discount: 30
  },
  {
    name: 'Daily Essentials Kit',
    price: 1899,
    description: 'Essential daily skincare routine',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/IMG-8316_73366387-5f49-45c0-b48c-4f74bcc57864_400x.jpg?v=1700684078'],
    category: 'bundles',
    rating: 4.6,
    numReviews: 89,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2499,
    discount: 25
  },
  {
    name: 'Luxury Night Care Set',
    price: 3799,
    description: 'Premium overnight treatment collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/TintTrio_img_400x.png?v=1675627371'],
    category: 'bundles',
    rating: 4.9,
    numReviews: 112,
    skinType: { all: true },
    stock: 65,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 4999,
    discount: 35
  },
  {
    name: 'Complete Beauty Bundle',
    price: 5999,
    description: 'Ultimate skincare collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/FuchsiaDuo-web_400x.png?v=1675239814'],
    category: 'bundles',
    rating: 4.8,
    numReviews: 178,
    skinType: { all: true },
    stock: 45,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 7999,
    discount: 40
  },
  {
    name: 'Gentle Cleansing Face Wash',
    price: 799,
    description: 'Gentle daily cleanser suitable for all skin types',
    images: ['https://ohlolly.com/cdn/shop/products/Urang_PurpleShieldEssence_Toner_7_1080x.jpg?v=1670464972'],
    category: 'face-wash',
    rating: 5,
    numReviews: 156,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 20
  },
  {
    name: 'Tea Tree Oil Face Wash',
    price: 849,
    description: 'Purifying face wash with tea tree oil',
    images: ['https://images.pexels.com/photos/6223482/pexels-photo-6223482.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'],
    category: 'face-wash',
    rating: 5,
    numReviews: 142,
    skinType: { oily: true, acne_prone: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1099,
    discount: 23
  },
  {
    name: 'Neem & Tulsi Face Wash',
    price: 699,
    description: 'Natural face wash with neem and tulsi extracts',
    images: ['https://i.pinimg.com/originals/ed/a9/6c/eda96c779e19e9ccd44bbf8954437e28.jpg'],
    category: 'face-wash',
    rating: 5,
    numReviews: 128,
    skinType: { all: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 899,
    discount: 22
  },
  {
    name: 'Charcoal Deep Clean Face Wash',
    price: 899,
    description: 'Deep cleansing face wash with activated charcoal',
    images: ['https://mybrightbody.com/cdn/shop/products/Custom-Skin-Care-Ayurvedic-Skin-Care-Mask_1200x.jpg?v=1688654208'],
    category: 'face-wash',
    rating: 5,
    numReviews: 98,
    skinType: { oily: true, combination: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'Vitamin C Brightening Face Wash',
    price: 999,
    description: 'Brightening face wash enriched with Vitamin C',
    images: ['https://venusaesthetics.pk/cdn/shop/files/DSC07626-Edit.jpg?v=1713219120'],
    category: 'face-wash',
    rating: 5,
    numReviews: 87,
    skinType: { all: true },
    stock: 110,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1299,
    discount: 23
  },
  {
    name: 'Aloe Vera Soothing Face Wash',
    price: 749,
    description: 'Soothing face wash with aloe vera extract',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/airbrush-facewash---product-image2_400x.jpg?v=1685018215'],
    category: 'face-wash',
    rating: 5,
    numReviews: 76,
    skinType: { sensitive: true, dry: true },
    stock: 95,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 25
  },
  {
    name: 'Anti-Acne Face Wash',
    price: 899,
    description: 'Specialized face wash for acne-prone skin',
    images: ['https://www.nirvanabotanics.com/cdn/shop/files/Glass-Skin-Bundle_06.jpg?v=1726493004'],
    category: 'face-wash',
    rating: 5,
    numReviews: 65,
    skinType: { oily: true, acne_prone: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'Cucumber Fresh Face Wash',
    price: 799,
    description: 'Refreshing face wash with cucumber extract',
    images: ['https://www.nirvanabotanics.com/cdn/shop/files/glowtonerpakistan.png?v=1717598847&width=1080'],
    category: 'face-wash',
    rating: 5,
    numReviews: 54,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 20
  },
  {
    name: 'Daily Care Face Wash Duo',
    price: 1499,
    description: 'Value pack of two daily care face washes',
    images: ['https://glowbeauty.pk/cdn/shop/files/nirvana-botanics-skin-care-nirvana-botanics-brightening-serum-30ml-40289815134465_1200x.png?v=1718270849'],
    category: 'face-wash',
    rating: 5,
    numReviews: 43,
    skinType: { all: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1899,
    discount: 21
  },
  {
    name: 'Complete Face Care Collection',
    price: 3999,
    description: 'Complete collection of face care products',
    images: ['https://www.petuniaskincare.com/cdn/shop/products/DPM_1-96_600x.jpg?v=1632964856'],
    category: 'face-wash',
    rating: 5,
    numReviews: 32,
    skinType: { all: true },
    stock: 45,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 4999,
    discount: 20
  },
  {
    name: 'Intense Hydration Moisturizer',
    price: 899,
    description: 'Deep hydrating moisturizer for intense skin nourishment',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/intense-hydration-bundle-2_1_400x.png?v=1699996289'],
    category: 'moisturizer',
    rating: 4.8,
    numReviews: 128,
    skinType: { dry: true, normal: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1299,
    discount: 30
  },
  {
    name: 'Skin Rescue Bundle',
    price: 999,
    description: 'Complete skin rescue moisturizing system',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/SkinRescueBundle-web_400x.png?v=1675267403'],
    category: 'moisturizer',
    rating: 4.9,
    numReviews: 95,
    skinType: { all: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1499,
    discount: 33
  },
  {
    name: 'Rosaline Moisturizer',
    price: 799,
    description: 'Soothing moisturizer for sensitive skin',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/rosaline---product-image2_1_400x.png?v=1676986731'],
    category: 'moisturizer',
    rating: 4.7,
    numReviews: 76,
    skinType: { sensitive: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 33
  },
  {
    name: 'Moisturizer Bundle',
    price: 1299,
    description: 'Complete moisturizing skincare set',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/Group1_400x.jpg?v=1690554340'],
    category: 'moisturizer',
    rating: 4.8,
    numReviews: 112,
    skinType: { all: true },
    stock: 75,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1799,
    discount: 28
  },
  {
    name: 'Tinted Lip Treatment Bundle',
    price: 849,
    description: 'Moisturizing lip treatment with tint',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Tinted-Lip-Treat-Bundle--product-image_400x.jpg?v=1681979111'],
    category: 'moisturizer',
    rating: 4.6,
    numReviews: 89,
    skinType: { all: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 29
  },
  {
    name: 'Hair Essential Duo',
    price: 1099,
    description: 'Essential moisturizing hair care duo',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/hair-essential-duo---product-image-01_400x.jpg?v=1687524443'],
    category: 'moisturizer',
    rating: 4.9,
    numReviews: 154,
    skinType: { all: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1599,
    discount: 31
  },
  {
    name: 'Final Mas Bundle',
    price: 949,
    description: 'Complete moisturizing skincare bundle',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/finalmas_400x.jpg?v=1667896859'],
    category: 'moisturizer',
    rating: 4.7,
    numReviews: 67,
    skinType: { all: true },
    stock: 95,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1399,
    discount: 32
  },
  {
    name: 'Saga Rapid Essential',
    price: 1199,
    description: 'Anti-aging moisturizing treatment',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Saga_Rapid_Essential_400x.png?v=1675278467'],
    category: 'moisturizer',
    rating: 4.8,
    numReviews: 93,
    skinType: { mature: true },
    stock: 70,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1699,
    discount: 29
  },
  {
    name: 'Ultimate Skin Corrector Bundle',
    price: 749,
    description: 'Skin correcting and moisturizing system',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/ultimate-skin-corrector-bundle---product-image_400x.png?v=1677241431'],
    category: 'moisturizer',
    rating: 4.6,
    numReviews: 45,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 25
  },
  {
    name: 'DSC Bundle',
    price: 1399,
    description: 'Premium moisturizing skincare bundle',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6372_400x.png?v=1716401109'],
    category: 'moisturizer',
    rating: 4.9,
    numReviews: 78,
    skinType: { all: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1999,
    discount: 30
  },
  {
    name: 'Vitamin C + E Serum',
    price: 1299,
    description: 'Powerful antioxidant serum with Vitamins C and E',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6847_400x.png?v=1717946422'],
    category: 'serums',
    rating: 5,
    numReviews: 124,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1599,
    discount: 19
  },
  {
    name: 'Niacinamide + Zinc Serum',
    price: 1199,
    description: 'Pore-refining serum with Niacinamide and Zinc',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6381.NEF_400x.png?v=1717946826'],
    category: 'serums',
    rating: 5,
    numReviews: 98,
    skinType: { oily: true, combination: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1499,
    discount: 20
  },
  {
    name: 'Hyaluronic Acid Serum',
    price: 1199,
    description: 'Deep hydrating hyaluronic acid serum',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/IMG_4990_400x.png?v=1643738840'],
    category: 'serums',
    rating: 5,
    numReviews: 87,
    skinType: { all: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1499,
    discount: 20
  },
  {
    name: 'Retinol Serum',
    price: 1399,
    description: 'Anti-aging retinol treatment serum',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/IMG_5005_400x.png?v=1643738570'],
    category: 'serums',
    rating: 5,
    numReviews: 76,
    skinType: { mature: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1699,
    discount: 18
  },
  {
    name: 'Peptide Complex Serum',
    price: 1499,
    description: 'Advanced peptide complex for skin renewal',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/IMG_5002_400x.png?v=1643784678'],
    category: 'serums',
    rating: 5,
    numReviews: 65,
    skinType: { all: true },
    stock: 75,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1799,
    discount: 17
  },
  {
    name: 'Brightening Serum Duo',
    price: 2299,
    description: 'Dual-action brightening serum set',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/serum-duo---product-image22_400x.png?v=1678266056'],
    category: 'serums',
    rating: 5,
    numReviews: 54,
    skinType: { all: true },
    stock: 70,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2899,
    discount: 21
  },
  {
    name: 'Anti-Aging Serum Bundle',
    price: 2499,
    description: 'Complete anti-aging serum collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/Ad-6webcopy_400x.jpg?v=1666955126'],
    category: 'serums',
    rating: 5,
    numReviews: 43,
    skinType: { mature: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3299,
    discount: 24
  },
  {
    name: 'Ultimate Skin Corrector Bundle',
    price: 3499,
    description: 'Premium skin correcting serum bundle',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/ultimate-skin-corrector-bundle---product-image_400x.png?v=1677241431'],
    category: 'serums',
    rating: 5,
    numReviews: 32,
    skinType: { all: true },
    stock: 50,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 4299,
    discount: 19
  },
  {
    name: 'Glow Boost Serum Duo',
    price: 2199,
    description: 'Radiance-boosting serum duo',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/serum-duo---product-image2_400x.png?v=1678266108'],
    category: 'serums',
    rating: 5,
    numReviews: 28,
    skinType: { all: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2799,
    discount: 21
  },
  {
    name: 'SPF Power Trio',
    price: 3299,
    description: 'Triple-action SPF serum collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/SPF-Power-Trio---product-image_400x.jpg?v=1682590509'],
    category: 'serums',
    rating: 5,
    numReviews: 19,
    skinType: { all: true },
    stock: 65,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 3999,
    discount: 18
  },
  {
    name: 'Daily Defense SPF 50+ Sunscreen',
    price: 999,
    description: 'High protection daily sunscreen with SPF 50+',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6874_400x.png?v=1717482337'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 156,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1299,
    discount: 23
  },
  {
    name: 'Ultra Light SPF 30 Sunscreen',
    price: 899,
    description: 'Lightweight daily sunscreen with SPF 30',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6902_400x.png?v=1719389704'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 142,
    skinType: { all: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'SPF Power Trio Bundle',
    price: 1099,
    description: 'Complete sun protection bundle with three products',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/SPF-Power-Trio---product-image_400x.jpg?v=1682590509'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 128,
    skinType: { all: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1399,
    discount: 21
  },
  {
    name: 'Mineral SPF 40 Sunscreen',
    price: 1199,
    description: 'Natural mineral sunscreen with SPF 40',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/001-WebImg_1_400x.png?v=1675257393'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 98,
    skinType: { sensitive: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1499,
    discount: 20
  },
  {
    name: 'Tinted SPF 35 Sunscreen',
    price: 1299,
    description: 'Tinted sunscreen for natural coverage with SPF 35',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/DSC6372_400x.png?v=1716401109'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 87,
    skinType: { all: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1599,
    discount: 19
  },
  {
    name: 'Sensitive Skin SPF 45 Sunscreen',
    price: 1099,
    description: 'Gentle sunscreen for sensitive skin with SPF 45',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/product-image-05_400x.png?v=1679135493'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 76,
    skinType: { sensitive: true },
    stock: 95,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1399,
    discount: 21
  },
  {
    name: 'Kids Safe SPF 50+ Sunscreen',
    price: 899,
    description: 'Kid-friendly sunscreen with maximum protection',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/WhatsAppImage2023-07-25at11.23.10AM_400x.jpg?v=1690266284'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 65,
    skinType: { sensitive: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'Sport SPF 50+ Sunscreen',
    price: 1199,
    description: 'Water-resistant sport sunscreen with SPF 50+',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/smoothie-cleansers---Product-images-01_400x.png?v=1679464259'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 54,
    skinType: { all: true },
    stock: 75,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1499,
    discount: 20
  },
  {
    name: 'Sun Protection Duo Pack',
    price: 1799,
    description: 'Value pack of two complementary sunscreens',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/tea-tree-cleansers---Product-images-01_400x.png?v=1679466208'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 43,
    skinType: { all: true },
    stock: 70,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 2299,
    discount: 22
  },
  {
    name: 'Complete Sun Care Collection',
    price: 4499,
    description: 'Ultimate sun protection skincare collection',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/Group1_250b63d3-9356-4993-9f2c-865c61778c7d_800x.jpg?v=1710136933'],
    category: 'sunscreen',
    rating: 5,
    numReviews: 32,
    skinType: { all: true },
    stock: 50,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 5999,
    discount: 25
  },
  {
    name: 'Hydrating Rose Toner',
    price: 899,
    description: 'Hydrating facial toner with natural rose extracts',
    images: ['https://www.tuffyorganics.com/cdn/shop/files/Group3_400x.jpg?v=1693310799'],
    category: 'toner',
    rating: 5,
    numReviews: 156,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'Calming Chamomile Toner',
    price: 799,
    description: 'Soothing toner with chamomile extract',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/IMG_3058_400x.png?v=1661247380'],
    category: 'toner',
    rating: 5,
    numReviews: 142,
    skinType: { sensitive: true },
    stock: 120,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 20
  },
  {
    name: 'Balancing Green Tea Toner',
    price: 849,
    description: 'Balancing facial toner with green tea extract',
    images: ['https://www.tuffyorganics.com/cdn/shop/products/IMG_3074_400x.png?v=1661247747'],
    category: 'toner',
    rating: 5,
    numReviews: 128,
    skinType: { combination: true, oily: true },
    stock: 90,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1099,
    discount: 23
  },
  {
    name: 'Soothing Aloe Vera Toner',
    price: 749,
    description: 'Gentle toner with soothing aloe vera',
    images: ['https://m.media-amazon.com/images/S/mms-media-storage-prod/final/BrandPosts/brandPosts/f205d127-069d-4cd2-9184-8903a9f748c3/f620cf91-045f-4662-acd5-126ca90ef62c/media._SL480_.jpeg'],
    category: 'toner',
    rating: 5,
    numReviews: 98,
    skinType: { sensitive: true, dry: true },
    stock: 85,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 25
  },
  {
    name: 'Brightening Vitamin C Toner',
    price: 999,
    description: 'Brightening toner enriched with Vitamin C',
    images: ['https://www.lookhealthystore.com/cdn/shop/products/07_aecfadc5-a5f0-45b4-b3db-e49f238590b5_800x.jpg?v=1646204086'],
    category: 'toner',
    rating: 5,
    numReviews: 87,
    skinType: { all: true },
    stock: 110,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1299,
    discount: 23
  },
  {
    name: 'Purifying Tea Tree Toner',
    price: 849,
    description: 'Purifying toner with tea tree oil',
    images: ['https://i.ebayimg.com/images/g/G8gAAOSwjU1imqxP/s-l500.jpg'],
    category: 'toner',
    rating: 5,
    numReviews: 76,
    skinType: { oily: true, acne_prone: true },
    stock: 95,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1099,
    discount: 23
  },
  {
    name: 'Nourishing Honey Toner',
    price: 899,
    description: 'Nourishing toner with natural honey',
    images: ['https://basicmadeco.com/cdn/shop/products/water-bank-blue-hyaluronic-essence-toner-for-combination-oily-skin2.webp?v=1678156597&width=800'],
    category: 'toner',
    rating: 5,
    numReviews: 65,
    skinType: { dry: true, normal: true },
    stock: 80,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1199,
    discount: 25
  },
  {
    name: 'Refreshing Cucumber Toner',
    price: 799,
    description: 'Refreshing toner with cucumber extract',
    images: ['https://m.media-amazon.com/images/I/61WIQfTPIdL.jpg'],
    category: 'toner',
    rating: 5,
    numReviews: 54,
    skinType: { all: true },
    stock: 100,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 999,
    discount: 20
  },
  {
    name: 'Hydration Duo Toner Set',
    price: 1599,
    description: 'Value pack of two hydrating toners',
    images: ['https://agtreasure.com/wp-content/uploads/2022/11/Its-Skin-Aloe-toner.png'],
    category: 'toner',
    rating: 5,
    numReviews: 43,
    skinType: { all: true },
    stock: 60,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 1999,
    discount: 20
  },
  {
    name: 'Complete Toner Collection',
    price: 3999,
    description: 'Complete collection of specialized toners',
    images: ['https://web.tradekorea.com/product/336/1726336/Skin%20Care%20cosmetic%20new%20aqua%20wonder%20moisture%20Toner_2.jpg'],
    category: 'toner',
    rating: 5,
    numReviews: 32,
    skinType: { all: true },
    stock: 45,
    seller: DEFAULT_SELLER_ID,
    originalPrice: 4999,
    discount: 20
  }
];

// Seeding function
const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert new products
    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products successfully`);

    mongoose.connection.close();
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedProducts();